cli/src/background_services.rs
cli/src/check.rs
cli/src/start.rs
linkup/src/lib.rs
linkup/src/memory_session_store.rs
linkup/src/name_gen.rs
linkup/src/server_config.rs
worker/src/kv_store.rs
worker/src/lib.rs

Some suggestions of code improvements.
Some of these are [Clippy](https://github.com/rust-lang/rust-clippy) lints and can be checked by using it.

refactor: suggestions for code improvement

---

cli/src/background_services.rs
cli/src/local_server.rs
cli/src/main.rs
cli/src/remote_local.rs
cli/src/start.rs
linkup/src/lib.rs
linkup/src/memory_session_store.rs
linkup/src/session_allocator.rs
worker/src/http_util.rs

This PR contains some suggestions for code cleanup.

chore: some code cleanup

---

linkup-cli/src/background_services.rs
linkup-cli/src/status.rs

Proper handle error where possible and where is not really an error that we can/want to handle, replace it with expect so that we can easier track down the failure.
From the [Rust book](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html):
> (...) the expect method lets us also choose the panic! error message. Using expect instead of unwrap and providing good error messages can convey your intent and make tracking down the source of a panic easier.
> In production-quality code, most Rustaceans choose expect rather than unwrap and give more context about why the operation is expected to always succeed. That way, if your assumptions are ever proven wrong, you have more information to use in debugging.

refactor(cli): replace .unwrap where possible

---

linkup-cli/src/background_tunnel.rs
linkup-cli/src/stop.rs
linkup/src/lib.rs

- Always remove pid files at the end of stop
- Swallow more no such process
Fixes DO-841

Better stop cleanup

---

linkup-cli/src/background_booting.rs
linkup-cli/src/main.rs
linkup-cli/src/reset.rs
linkup-cli/src/start.rs
linkup-cli/src/stop.rs

Devs are using reset a lot. Make it do what it says on the tin and not reset local/remote configuration

Reset does not clear local/remote settings

---

linkup-cli/src/main.rs
linkup-cli/src/remote_local.rs
linkup-cli/src/start.rs

Remove some unnecessary clones when sending data into commands.

refactor: remove unnecessary clones

---

linkup-cli/src/local_server.rs
linkup-cli/src/services/caddy.rs
linkup/src/headers.rs
linkup/src/lib.rs

Host really seemed to be screwing things up, I found it better to remove the header instead

Make iframes work cross domain

---

.github/workflows/ci.yml
linkup/src/lib.rs
worker/src/lib.rs

Funky miss! Odd side effects...

Fix traceparent not set on forward host bug

---

linkup-cli/src/main.rs

Add version command to cli

---

Cargo.lock
linkup-cli/Cargo.toml
linkup-cli/src/local_server.rs
linkup/src/headers.rs
linkup/src/lib.rs

- when local-dns is enabled, folded cookies can come through the local server

Unfold cookies on local server

---

README.md
docs/using-linkup.md
linkup-cli/src/main.rs

Add troubleshooting / extra docs on running linkup + local-dns

Add more docs for running linkup

---

Cargo.lock
linkup-cli/Cargo.toml
linkup-cli/src/background_booting.rs
linkup-cli/src/env_files.rs

Solves visiting the tunnel too quickly causes ip problems

Wait 5 seconds for cloudflare tunnel to start

---

clear-unused-dns.ts

This is why local-dns has been broken, we've been out of records!

Add dns cleanup script for acme records

---

Cargo.lock
linkup-cli/Cargo.toml
linkup-cli/src/main.rs
linkup-cli/src/start.rs
linkup-cli/src/tunnel.rs

Resolves DO-1379
If PAID_TUNNELS is set, run paid tunnels, otherwise, free.

feat(ci): paid-tunnels opt-in

---

linkup-cli/src/file_system.rs
linkup-cli/src/main.rs
linkup-cli/src/start.rs
linkup-cli/src/tunnel.rs

feat: create tests for start_paid_tunnel

---

linkup-cli/src/paid_tunnel.rs
linkup-cli/src/start.rs

Cleanup unit tests

---

linkup-cli/src/background_booting.rs
linkup-cli/src/local_config.rs
linkup-cli/src/services/tunnel.rs
linkup-cli/src/start.rs

This makes is_paid backwards compatible with old state files

Move is_paid to Optional linkup config state

---

clear-unused-dns.ts
linkup-cli/src/commands/health.rs
linkup-cli/src/commands/start.rs
linkup-cli/src/local_config.rs
linkup-cli/src/services/cloudflare_tunnel/mod.rs
linkup-cli/src/services/cloudflare_tunnel/paid_tunnel.rs

- remove is_paid from state file - replace with paid zone id data
- no more need for zone id env var
- get a suitable zone straight from the api tokens permissions

Remove hardcoded mentimeter tunnel name

---

.github/workflows/caddy.yml

Add workflow to build caddy with our linkup modules.

Add caddy build workflow

---

Cargo.lock
linkup-cli/Cargo.toml
linkup-cli/src/commands/start.rs
linkup/Cargo.toml
local-server/Cargo.toml
rust-toolchain.toml
server-tests/Cargo.toml
server-tests/tests/ws_test.rs
worker/Cargo.toml

Tests pass, did local testing of the cli also, feels good!

Update all dependencies to latest

---

clear-unused-dns.ts
linkup-cli/src/commands/health.rs
linkup-cli/src/commands/start.rs
linkup-cli/src/local_config.rs
linkup-cli/src/services/cloudflare_tunnel/mod.rs
linkup-cli/src/services/cloudflare_tunnel/paid_tunnel.rs

Reverts mentimeter/linkup#140 - Causing tunnels to be created in the wrong zones

Revert "Remove hardcoded mentimeter tunnel name"

---

worker/src/lib.rs
worker/src/tunnel.rs

feat: generate random secret for tunnel

---

linkup-cli/src/local_config.rs
linkup-cli/src/services/cloudflare_tunnel.rs
linkup-cli/src/worker_client.rs
server-tests/tests/helpers.rs
server-tests/tests/server_test.rs
worker/src/lib.rs
worker/wrangler.toml.sample

feat: put all `/linkup*` endpoints behind auth

---

worker/src/routes/certificate_cache.rs

Caddy storage Linkup is now sending this query
https://github.com/mentimeter/caddy-storage-linkup/commit/9922a4d9f7636ab93d9dfcf63fa9cb50f3ac3421

feat(certificates): handle query params from client when listing keys

---

linkup-cli/src/commands/deploy/cf_deploy.rs
linkup-cli/src/commands/deploy/resources.rs

Moved the cache rule to its own descriptor for this specifically, I think it will do well enough for now.

Only create cache rules on tunnel zone for tunnel cache rule

---

linkup-cli/src/commands/deploy/cf_deploy.rs
linkup-cli/src/commands/deploy/resources.rs

feat(cli): build linkup account token name from zones

---

Cargo.lock
linkup-cli/src/commands/deploy/api.rs
linkup-cli/src/commands/deploy/resources.rs
worker/Cargo.toml
worker/src/lib.rs
worker/src/routes/certificate_cache.rs
worker/src/routes/certificate_cache_lock.rs
worker/src/routes/mod.rs
worker/wrangler.toml.sample

Reference for the storage support: https://github.com/mentimeter/caddy-storage-linkup/pull/1
Closes DO-1960

feat(worker): implement lock mechanism for certificate cache

---

cloudflare/src/endpoints/dns.rs
cloudflare/src/lib.rs
cloudflare/src/linkup.rs
linkup-cli/src/commands/deploy/cf_deploy.rs
linkup-cli/src/commands/deploy/cf_destroy.rs
linkup-cli/src/commands/deploy/resources.rs
worker/src/lib.rs

feat: delete all tunnels on infra destroy

---

Cargo.lock
linkup-cli/Cargo.toml
linkup-cli/src/commands/health.rs
linkup-cli/src/commands/local.rs
linkup-cli/src/commands/remote.rs
linkup-cli/src/commands/status.rs
linkup-cli/src/commands/update.rs
linkup-cli/src/local_config.rs
linkup-cli/src/main.rs
linkup-cli/src/release.rs

This will be merged to release 3.1.0.
Changelog:
- #227 
- #228
- #230 
- #231

`next` tracking PR for `3.1.0`

---

Cargo.lock
local-server/Cargo.toml

Makes websocket requests to tls remotes work

Add rustls feature to tokio tungstenite in local server

---

Cargo.lock
linkup-cli/Cargo.toml
linkup-cli/src/commands/health.rs
linkup-cli/src/commands/start.rs
linkup-cli/src/commands/status.rs
linkup-cli/src/commands/update.rs
linkup-cli/src/local_config.rs
linkup-cli/src/release.rs
linkup-cli/src/services/local_server.rs
linkup/src/versioning.rs
local-server/src/lib.rs
local-server/src/ws.rs

Changelog:
- #241 
- #244
- #245 
- #246 
- #243 
- #248

`next` tracking PR for version `3.4.0`

---

local-server/src/lib.rs

When proxying WebSocket connections over two hops via the Cloudflare worker and the linkup local server, we have found that there are cases where content encoding and content length headers exist in the upstream response from the underlying local server.
When those headers exist in a WebSocket handshake, Cloudflare workers completely denies the WebSocket connection. 
These headers shouldn't make sense in a WebSocket proxying scenario since they are only valid for HTTP response bodies which shouldn't exist when using WebSockets.

Deny content encoding and length headers when proxying websockets
