mentimeter/linkup

- linkup-cli/src/local_server.rs
- linkup/src/lib.rs
- linkup/src/session.rs
- linkup/src/session_allocator.rs
This PR suggests the change of the methods for conversion to leverage the [From](https://doc.rust-lang.org/std/convert/trait.From.html) \ [TryFrom](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) traits.
- Rename `input_yaml_conf` to `input_json_conf` since it seems like the default now is to use JSON.
- Change the responsibility of who needs to verify the structural validity of the input (JSON/YAML). With the current proposal, the Session is constructed from a format validated value (`serde_json::Value`/`serde_yaml::Value`) and the caller is the one responsible for handling invalid format.
> refactor: ergonomic conversions

- Cargo.lock
- linkup/Cargo.toml
- linkup/src/lib.rs
- linkup/src/session.rs
This PR moves from YAML to JSON.
Note: the tests are currently not passing on `main`, and consequently not passing here. Haven't had time to look into it.
> refactor: move linkup from YAML to JSON

- linkup-cli/src/status.rs
This PR uses [MPSC](https://doc.rust-lang.org/std/sync/mpsc/) on the status command to improve performance.
From:
To:
**_Note: Benchmarks include one `timeout`_**
> feat: introduce MPSC on the status command

- linkup-cli/src/status.rs
This PR adds color to the warning that is printed before exiting the program.
The idea behind this is to draw more attention to this message regarding possible issues with services.
> style: highlight services status warning

- linkup-cli/src/signal.rs
- linkup-cli/src/stop.rs
Fixes a few retry failure cases I've seen
> Ignore no such process when stopping tunnel

- linkup-cli/src/local_server.rs
- linkup/src/lib.rs
- worker/src/lib.rs
- worker/src/ws.rs
Case is, target service on the remote side is a tunnel.
If the path gets rewritten once remotely, it can throw off finding the right service in the local server.
Solution: an extra header linkup-destination set on every hop. If the destination has been calculated once, we reuse it on later hops.
> Fix overlapping route rewrites

- linkup-cli/src/background_tunnel.rs
- linkup-cli/src/local_config.rs
- linkup-cli/src/local_dns.rs
- linkup-cli/src/local_server.rs
- linkup-cli/src/main.rs
- linkup-cli/src/reset.rs
- linkup-cli/src/services/caddy.rs
- linkup-cli/src/services/dnsmasq.rs
- linkup-cli/src/services/mod.rs
- linkup-cli/src/signal.rs
- linkup-cli/src/start.rs
- linkup-cli/src/status.rs
- linkup-cli/src/stop.rs
- linkup/src/lib.rs
- linkup/src/session_allocator.rs
- worker/src/http_util.rs
Makes it possible to install local DNS routing for linkup.
Uses of a combination of [caddy](https://caddyserver.com/) and [dnsmasq](https://thekelleys.org.uk/dnsmasq/doc.html) to achieve local TLS/SSL and DNS for this to work in a frictionless way.
> feat: add local-dns command

- linkup-cli/src/start.rs
- linkup-cli/src/stop.rs
With this new change, when writing the new variables, Linkup will start by adding a new line to avoid writing the header on the same line as the latest variable. On cleanup, it will also remove the wrapping new lines around the Linkup block (if any).
So, for example:
An existing config:
```
```
After start
```
...
...
...
```
After stop
```
```
Or an existing config:
```
a
b
c
```
After start
```
a
b
c
...
...
...
```
After stop
```
a
b
c
```
Or even if modified between start and stop, where existing is:
```
a
b
c
```
After start
```
a
b
c
...
...
...
```
Then modified to
```
a
b
c
...
...
...
d
e
```
After stop
```
a
b
c
d
e
```
> refactor: handle new lines to avoid interfering with existing variables

- linkup-cli/src/env_files.rs
- linkup-cli/src/main.rs
- linkup-cli/src/start.rs
- linkup-cli/src/stop.rs
Move env file handling to own module so that we can better test its behaviour and have it contained.
We need the service name on the env file handling just so that we can use that while building the `CliError`. It feels that maybe we can return another type of error by the env handlers and leave the translation into a `CliError` as a responsibility of the caller. But maybe we can do that on another PR.
> refactor: extract env file handling

- .github/workflows/ci.yml
- e2e/src/main.rs
- linkup-cli/src/background_tunnel.rs
- linkup-cli/src/remote_local.rs
- worker/src/lib.rs
- worker/src/ws.rs
This PR adds Clippy to the CI.
- Replace unmaintained actions-rs actions.
- Add step on the check to also run Clippy.
- Fix issues risen by Clippy.
- Shorten the name of the workflow from "Continuous integration" to simply "CI".
There seems to be an issue with using Arc for non Sync/Send type when handling `CfWorkerStringStore`. Clippy is bringing that up, that is why I had to explicitly allow it, but we should revisit and try to fix it.
For more information check: https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
> feat: add Clippy to CI

- Cargo.lock
- Cargo.toml
- linkup-cli/Cargo.toml
- linkup-cli/src/local_server.rs
- linkup/Cargo.toml
- linkup/src/headers.rs
- linkup/src/lib.rs
- linkup/src/session_allocator.rs
- worker/Cargo.toml
- worker/src/http_util.rs
- worker/src/lib.rs
- worker/src/ws.rs
This should improve the ergonomics around handling headers and change its types between different libraries.
- Introduce [`unicase`](https://docs.rs/unicase/latest/unicase/) to `linkup` so that headers can be handled with case insensitive.
- Add feature flags to `linkup`.
- `reqwest`: add `reqwest` as dependency and implement helper methods around `linkup::HeaderMap` to work with `reqwest` headers. 
- `actix`: add `actix-web` and `actix-http` as dependencies and implement helper methods around `linkup::HeaderMap` to work with `actix` request and headers. 
- `worker`: add `worker` as dependency and implement helper methods around `linkup::HeaderMap` to work with `worker` request and headers.
- Changes from `.clone` to use reference where applicable.
- Move `Host` header definition into the …
> refactor: rework headers ergonomics

- linkup-cli/src/local_server.rs
- linkup/src/lib.rs
- linkup/src/session_allocator.rs
- worker/src/lib.rs
- worker/src/ws.rs
Previously the `SessionAllocator` was designed to have an `Arc<dyn StringStore>`, which caused a [Clippy issue regarding internal of Arc not being Send or Sync](https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync).
For the use case of `SessionAllocator`, it doesn't need to have an internal `Arc` to the `StringStore`, a simple reference seems to be enough.
> refactor: remove unnecessary Arc in SessionAllocator

- linkup/src/lib.rs
- linkup/src/name_gen.rs
Remove code for generating a new session name and for generating a unique animal key from inside `name_gen.rs`. It seems like this code now [resides on the `SessionAllocator`](https://github.com/mentimeter/linkup/blob/5a8458adf3b0a3814084fb52ad284a0600e518b8/linkup/src/session_allocator.rs#L115-L159) and that this one is not used anywhere else.
> chore: remove unused name generation code

- linkup/src/session_allocator.rs
After the merge of #37, it was introduced a new way to access the headers. It seems like these ones weren't updated to use the new enum to access the header. This commit changes to use the enum instead of raw strings on those places.
> chore: use HeaderName instead of raw string

- linkup-cli/src/main.rs
- linkup-cli/src/start.rs
- linkup-cli/src/stop.rs
Config is always optional for the commands that use it, so instead of repeating it on all commands, we can move it to the cli arguments so that any command that would like to use this option, could do so.
> refactor: move config to cli arguments instead of command

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup/src/lib.rs
Use the full linkup domain as X-Forwarded-Host. This is "truer" to the standard, should still work with the rest of the linkup session detection functions, and makes some next features work for us.
> X-Forwarded-Host to contain full linkup domain

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/local_server.rs
This does not make it work when using a cloudflare worker / tunnel. 
The wasm client of reqwest does not support their "redirect policies" yet:
https://github.com/seanmonstar/reqwest/blob/master/src/wasm/client.rs
> Do not follow redirects on local linkup server

- Cargo.lock
- linkup/Cargo.toml
- linkup/src/lib.rs
- linkup/src/memory_session_store.rs
- linkup/src/session_allocator.rs
- worker/src/kv_store.rs
- worker/src/lib.rs
- worker/src/ws.rs
With the release of [Rust 1.75](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html#async-fn-and-return-position-impl-trait-in-traits), the first round of stabilization of async in traits is out! This does come with its own [set of caveats](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#where-the-gaps-lie). But those seem to be mostly for public traits and issues with bounds. The trait that we use it is, theoretically, public. But we intend it to be used by the other modules within the workspace, so it seems like it might be fine to move from the async-trait.
It might be good to test on the worker scenario, since there might be something there that I'm missing, but it seems by the tests and checks that is all working.
> refactor: remove dependency on async-trait

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/local_config.rs
- linkup-cli/src/services/caddy.rs
supports *.api.mentimeter.dev for example
> Use all domains in caddy config

- linkup/src/headers.rs
- linkup/src/lib.rs
- worker/src/http_util.rs
- The underlying wasm/rust bindings seem to be folding cookies. getSetCookie is not a valid web_sys function yet..
- This is not-exhaustive cookie unfolding. Quotes, for example, are not yet supported
> Unfold worker response cookies

- linkup/src/session.rs
- worker/src/lib.rs
- For preview environments, allow much more to be cached
- Ensure only GET methods are cached
> Improve worker caching logic

- linkup-cli/src/env_files.rs
When looking into the start index of the matching, it gets the index of the initial matching char. Which means that to get the last char, we should add the size of the separator - 1 to take into consideration that the index start on the first char.
> fix: off by one error env file without new line

- Cargo.lock
- linkup/Cargo.toml
- linkup/src/name_gen.rs
- linkup/src/session_allocator.rs
- This allows preview environments to keep the same url over multiple underlying deployments, as long as the linkup config doesn't change
> Use deterministic 6 char names for preview envs

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/local_dns.rs
- linkup-cli/src/services/caddy.rs
- Lets engineers share letsencrypt storage
- Reduces the amount of calls we make to letsencrypt
- Reduces the amount of rate limits we hit
> Enable redis as a caddy shared storage module

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/main.rs
https://linear.app/mentimeter/issue/DO-1380/add-linkup-docs-links-to-the-help-command
> doc: add link to linkup docs in help command

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/file_system.rs
- linkup-cli/src/main.rs
- linkup-cli/src/start.rs
- linkup-cli/src/tunnel.rs
- random tunnel secret
- test save credentials.
- Send the contents of files in write_files as a string instead of bytes for simpler debugging.
> feat: random tunnel secret

- linkup-cli/src/file_system.rs
- linkup-cli/src/start.rs
- linkup-cli/src/tunnel.rs
- Test the two main paths for `create_config_yml`, 1) `.cloudflared` directory exists and 2) doesn't exist. 
- Ensure that all "real" file system operations are mocked and don't actually create real files.
- Align some variable naming across files
- Rename the param `fs` -> `filesys` to avoid confusion with `std::fs`
> Ensure that file system operations are mocked

- linkup/src/session.rs
- The cache was being over-used and caching 4xx requests
- The cache was being used even with no cache control
For now, use cache: None on preview environments
> Default preview cache routes to None

- linkup-cli/src/local_config.rs
- linkup-cli/src/start.rs
- linkup/src/session.rs
Also added the `Debug` trait to `LocalState` which makes it possible to 
```
println!("{:?}", state);
```
which can be useful for debug logging and troubleshooting.
part of do-1497
> Add tests to start.rs

- Cargo.lock
- clear-unused-dns.ts
- linkup-cli/Cargo.toml
- linkup-cli/src/background_booting.rs
- linkup-cli/src/paid_tunnel.rs
- linkup-cli/src/services/tunnel.rs
- linkup-cli/src/start.rs
Tested going from paid to free tunnel, and vice versa. Works smoothly for me at least 🤞 
Some extra logging added that shows up when running `RUST_LOG=info cargo run -- start`. There is more that can be done with logging but will leave that for the linear card DO-1495 "linkup: logger".
Part of DO-1495
Resolves DO-1496
> feat: paid tunnels v1

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/start.rs
Sets env vars for both paid and free tunnels
> fix: set linkup env vars in .envs

- linkup-cli/src/local_config.rs
- linkup/src/session.rs
- server-tests/tests/server_test.rs
Allow preview sessions to use the same `cache_routes` allowlist as normal environments. This means we can cache _next/static which reduces the load on heroku dynos
> Allow preview sessions to have cache_routes

- Cargo.lock
- linkup-cli/src/start.rs
- linkup-cli/src/status.rs
When we check the status of a service, we are not sending the extra headers, like we do for normal requests. With this change, we make sure to add the additional requests to the services when doing status check as well.
Closes DO-1755
> fix: use additional headers on status request

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup/Cargo.toml
- local-server/Cargo.toml
- server-tests/Cargo.toml
- worker/Cargo.toml
- worker/src/ws.rs
- `worker` dependency could not be bumped because of wasm bindings issue.
- Skipped the bump of `reqwest` since it need some additional changes for `rustls`. The change required seems to be related to `CryptoProviders` (more details on the changelog for [rustls](https://github.com/rustls/rustls/releases/tag/v%2F0.23.0))
- Removed direct dependency on `wasm-bindgen-futures` and instead started to use the one re-exported by `worker` to ensure same version.
> chore: bump dependencies

- linkup-cli/Cargo.toml
- worker/Cargo.toml
The following warnings are fixed by these changes:
- warning: version requirement `0.9.34+deprecated` for dependency `serde_yaml` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
- warning: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition (in the `axum` dependency)
> chore: fix Cargo warnings

- Cargo.lock
- rust-toolchain.toml
- worker/Cargo.toml
This also pin the Rust toolchain to 1.81.0. We can look into removing this pin once the issue between the wasm bindings between 1.82 and Node 18.
- https://github.com/rustwasm/wasm-bindgen/issues/4211
- https://github.com/cloudflare/workers-rs/issues/654
> chore: bump `worker-rs` 0.3.0 -> 0.4.2

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/main.rs
- linkup-cli/src/preview.rs
- linkup-cli/src/status.rs
This PR improves the feedback of the status command to live update the services responses. One "breaking change" is the removal of the --all/-a option. With the idea to give better visibility of the overall status, that option doesn't make that much sense. (we can of course add it back if we think is very important here).
Changelog:
- Removed --all/-a options. Now all services are shown by default.
- Added dependency to [`crossterm`](https://docs.rs/crossterm/latest/crossterm/) to manipulate the terminal output.
- Cleaned up the output (removed "Service information:" and "Session information:" headers).
- Services statuses are update as soon as we get them.
- Removed `component_kind: linkup`. Internal Linkup services are reported as remote or local accordingly.
- Added priority option for …
> feat: revamp status command

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/start.rs
When we run free tunnels, we check if there is any local service already running to warn the user about it. We are currently not doing this for paid tunnels as well.
This PR adds the same check for paid tunnels.
> feat: check running services when using paid tunnel

- linkup-cli/src/status.rs
This should help visualize services that are pointing to local when running `linkup status`.
Example:
> feat: highlight local services on `status` command

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/health.rs
- linkup-cli/src/main.rs
We have very often to instruct people to do some steps and verify some local settings so that we can have an idea of what might be wrong with their environment.
It would be good for Linkup to have a command that output the overall health so that we can just get the dump from this command and have an idea of what might be wrong.
```
System info:
OS: Darwin (14.6.1)
Session info:
Name: sandy-camel
Background sevices:
- Caddy       RUNNING (76550)
- dnsmasq     RUNNING (76565)
- Cloudflared RUNNING (76530)
Environment variables:
- LINKUP_CF_API_TOKEN          OK
- LINKUP_CLOUDFLARE_ZONE_ID    OK
- LINKUP_CLOUDFLARE_ACCOUNT_ID OK
Linkup:
Version: 1.2.1
Config location: $HOME/.linkup
Config contents:
- dnsmasq-log
- localserver-stdout
- dnsmasq-pid
- localserver-pid
- cloudflared-pid
- …
```
> feat: create health command

- linkup-cli/src/start.rs
- linkup-cli/src/status.rs
- [fix: ensure cursor is displayed back in case of ctrl+c](https://github.com/mentimeter/linkup/commit/2dd252784a0fe21a5bda6243eb55f7a16daf66b3)
- [style: make status output more compact](https://github.com/mentimeter/linkup/commit/a5cccffbe192feb547b63e733c45bad1c3fd2ba3)
- [lint: remove unnecessary return](https://github.com/mentimeter/linkup/commit/06e39886875fc4b1d1acf93e29b0cc06d0c402be)
> chore: small QOL improvements

- linkup-cli/src/background_booting.rs
- linkup-cli/src/paid_tunnel.rs
- linkup-cli/src/reset.rs
- linkup-cli/src/services/tunnel.rs
- linkup-cli/src/start.rs
First in a series of PRs to simplify the background booting logic in the cli.
- Remove the `boot_background_services` function in favour of only using more specific ones (`boot_local_dns` etc)
- Moved more of the logic surrounding paid vs free tunnels to the same place
- Some opinionated variable renames
> Untangle background boot cleanup 1

- linkup-cli/src/status.rs
These changes aim to solve the issue of running status when the terminal window is too small. Now, if the window is <110 the `LOCATION` column will be hidden, and if it is <50 the `COMPONENT KIND` will also be hidden. It will also live update if the window is resized.
> feat: size adjustable `status` table

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/local_config.rs
- linkup-cli/src/main.rs
- linkup-cli/src/services/caddy.rs
- linkup-cli/src/services/cloudflare_tunnel/mod.rs
- linkup-cli/src/services/dnsmasq.rs
- linkup-cli/src/start.rs
- linkup-cli/src/stop.rs
- linkup-cli/src/worker_client.rs
To be merged after #123 
- feat: new dynamic `status` (#122)
- fix: unable to set session name on first run (#123)
> chore: bump linkup-cli 1.4.0 -> 1.5.0

- linkup-cli/src/health.rs
- linkup-cli/src/services/caddy.rs
- linkup-cli/src/services/cloudflare_tunnel/mod.rs
- linkup-cli/src/services/dnsmasq.rs
- linkup-cli/src/services/local_server.rs
- linkup-cli/src/services/mod.rs
Example of the new background services:
Changelog:
- Add `architecture` to the System information.
- Add Local Linkup server to the list of background services.
- Show on the health if the background service is not installed.
- When the service is running, look at the pid from its pidfile.
> feat: add more information on `health`

- linkup-cli/src/commands/local_dns.rs
- linkup-cli/src/services/caddy.rs
- linkup-cli/src/services/dnsmasq.rs
This should fix cases where starting Linkup on a system that does not have `/etc/resolver` setup would break.
Now it will skip both `caddy` and `dnsmasq` if the folder is not found.
> feat: skip Dnsmasq and Caddy if can't read /etc/resolver

- .github/workflows/release.yml
[Apparently there is Homebrew on Linux.](https://docs.brew.sh/Homebrew-on-Linux) This changes so that we update the linkup.rb to also have the correct paths to the Linux assets. Changes on the homebrew-mentimeter repo will be needed so that this works as expected.
Blocked by: https://github.com/mentimeter/homebrew-mentimeter/pull/2
> feat: add Linux release to Homebrew

- linkup-cli/src/commands/deploy/api.rs
As per [documentation of the Caddy Cloudflare DNS module](https://github.com/caddy-dns/cloudflare?tab=readme-ov-file#configuration), the token that we will use need:
> `Zone.Zone:Read` and `Zone.DNS:Edit` permissions for `All zones`
So this PR changes the token that will be created to have that.
> fix: use the necessary policies for the Cloudflare Account token

- linkup-cli/src/commands/deploy/api.rs
- linkup-cli/src/commands/deploy/cf_deploy.rs
- linkup-cli/src/commands/deploy/resources.rs
- this makes the linkup.mycloudflareaccount.workers.dev domain work when linkup is deployed
> Enable worker subdomain on linkup worker deploy

- Cargo.lock
- worker/Cargo.toml
- worker/src/routes/certificate_cache.rs
These endpoints will be consumed by https://github.com/mentimeter/caddy-storage-linkup
> feat: implement certificate cache endpoints

- linkup-cli/src/commands/health.rs
- linkup-cli/src/local_config.rs
- linkup-cli/src/services/caddy.rs
With this change, the config file will need a new required field: `worker_token`. This should be the token to be sent to the linkup.remote (worker) when making requests.
Closes DO-1928
> feat: move worker token to config instead of env

- linkup-cli/src/commands/deploy/resources.rs
> Invalid Worker name. Ensure the name is lowercase, alphanumeric, and contains no spaces or special characters except dashes.
😬
> fix: ensure only dashes on worker name

- linkup-cli/src/commands/update.rs
We are storing the format different than the one that we are trying to read, so this is not working. This should fix the issue by storing the expected `CachedLatestRelease`.
> fix: latest release cache file format

- Cargo.lock
- cloudflare/src/endpoints/workers/mod.rs
- cloudflare/src/framework/response/mod.rs
- linkup-cli/Cargo.toml
- linkup-cli/src/commands/deploy/cf_deploy.rs
- linkup-cli/src/commands/deploy/resources.rs
- worker/src/lib.rs
- worker/wrangler.toml.sample
Related changes:
- https://github.com/mentimeter/caddy-storage-linkup/commit/f7326fea11ebbc9ca6c61cfab48e11c9b1ca080d
- https://github.com/mentimeter/caddy-dns-linkup/commit/f80bbfcbeb0d0d7c51d8e7ffab8b789c0ccfc344
Closes DO-1928
> feat: add authentication to `/linkup/certificate*` endpoints

- cloudflare/src/endpoints/workers/list_schedules.rs
- cloudflare/src/endpoints/workers/mod.rs
- cloudflare/src/endpoints/workers/upsert_schedules.rs
- linkup-cli/src/commands/deploy/cf_deploy.rs
- linkup-cli/src/commands/deploy/resources.rs
- worker/src/lib.rs
- worker/src/tunnel.rs
- worker/wrangler.toml.sample
> feat: scheduled clean up of unused tunnels

- Cargo.lock
- linkup-cli/Cargo.toml
- linkup-cli/src/worker_client.rs
- worker/src/lib.rs
This will also start do decline requests from clients that are older than the minimum supported version.
The minimum supported version is being set as 2.1.0, which is the one being released by this change.
> feat(cli,worker): send header to worker with client version

- cloudflare/src/endpoints/workers/mod.rs
- linkup-cli/src/commands/deploy/resources.rs
```
The following changes are needed:
DeployPlan {
kv_actions: [],
script_action: Some(
Upload {
script_name: "linkup-worker-xxx",
metadata: WorkerMetadata {
main_module: "shim.mjs",
bindings: [
KvNamespace {
name: "LINKUP_SESSIONS",
namespace_id: "<to-be-filled-on-deploy>",
},
KvNamespace {
name: "LINKUP_TUNNELS",
namespace_id: "<to-be-filled-on-deploy>",
},
KvNamespace {
name: "LINKUP_CERTIFICATE_CACHE",
namespace_id: "<to-be-filled-on-deploy>",
},
PlainText {
name: "WORKER_TOKEN",
text: "yayitworks",
},
],
compatibility_date: "2024-12-18",
tag: "127b05e1728dc8ee41e1e9f91c2d9936720b4efe048ab5a20758d0c15e7c87ff",
},
parts: [
WorkerScriptPart {
name: "shim.mjs",
content_type: "application/javascript+module",
},
WorkerScriptPart {
name: "index.wasm",
content_type: "application/wasm",
},
], …
```
> Maintain linkup worker token across deploys

- .github/workflows/caddy.yml
The Caddy build workflow has not being triggered automatically when the tag is created on release. It seems like the format is correct, following the GitHub docs:
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
But it is not working as expected. This changes from using `[0-9]+.[0-9]+.[0-9]+` to using `[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*` in an attempt to fix the triggering.
Closes DO-1965
> fix(ci): Caddy workflow not being triggered

- .github/workflows/release.yml
- linkup-cli/Cargo.toml
- linkup-cli/build.rs
- linkup-cli/src/commands/deploy/resources.rs
Currently to run the build of the CLI, it is necessary to run the worker build before:
```
cargo install -q worker-build && worker-build --release
```
Now the worker will be built automatically when building the CLI if there has been any changes to worker source code.
- Build scripts - https://doc.rust-lang.org/cargo/reference/build-scripts.html
> feat(cli): build worker automatically when building cli

- linkup-cli/src/commands/uninstall.rs
- linkup-cli/src/commands/update.rs
- linkup-cli/src/main.rs
This points homebrew installations to use `brew upgrade` instead of `linkup update`.
> feat(cli): better handle different installation methods

- linkup-cli/build.rs
Currently since both are being built on the same CARGO_TARGET_DIR, the main build is locking the worker build from running.
This issue was introduced on https://github.com/mentimeter/linkup/pull/192
> fix: build worker on a different target dir to avoid locking

- linkup-cli/install.py
- linkup-cli/src/commands/health.rs
- linkup-cli/src/commands/update.rs
**What's done**
- using `setcap` in Linux to be able to bind ports
- for install
- for update
- changed the Heath command to say whether the capability is set or not
> feat(cli): set port binding capability on binary for Linux

- linkup-cli/src/commands/health.rs
- linkup-cli/src/commands/local_dns.rs
- linkup-cli/src/commands/mod.rs
- linkup-cli/src/commands/server.rs
- linkup-cli/src/commands/start.rs
- linkup-cli/src/commands/stop.rs
- linkup-cli/src/commands/uninstall.rs
- linkup-cli/src/local_config.rs
- linkup-cli/src/main.rs
- linkup-cli/src/services/mod.rs
- local-server/src/certificates/mod.rs
There's no such cli tool like `security` on Ubuntu, so everything is mostly manual.
**Where do certs live in Linux**
Certs live in `/etc/ssl/certs`, but this directory is mostly a collection of symlinks that shouldn't be updated directly.
Instead, we copy our cert to `/usr/local/share/ca-certificates` and then run `update-ca-certificates` to update the symlinks.  
**Where do Firefox certs live in Linux**
Depends!
I found three places depending on how Firefox was installed and what your Linux is.
```
let profile_dirs = [
".mozilla/firefox",
"snap/firefox/common/.mozilla/firefox",
".var/app/org.mozilla.firefox/.mozilla/firefox",
];
```
**How to test**
- pull the branch on a Ubuntu machine
- `cd linkup-cli && cargo install --path .`
- `cd ..` — get back to the root of the repo
- `sudo setcap …
> feat(certificates): add self-signed certs on Ubuntu

- linkup-cli/src/commands/health.rs
macOS doesn’t expose each thread as a “full” process.
However, Linux does. Which results in lots of thread-duplicates on `linkup health` on Linux.
[From the Apple documentation](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/CreatingThreads/CreatingThreads.html?utm_source=chatgpt.com)
> Each process (application) in OS X or iOS is made up of one or more threads, each of which represents a single path of execution through the application's code.
Whereas in Linux, a thread is a process on its own.
> fix(linkup-cli): fix thread-duplicates on linkup health list of orphans 

- linkup-cli/src/services/local_server.rs
- local-server/src/lib.rs
- local-server/src/ws.rs
- In order for websockets to work well, they must respect websocket headers like `sec-websocket-key`
- One way to do this as a proxy is to "not" and just pass all headers along
- This modifies the local server websocket implementation to pass more headers upstream _and_ downstream, so that more gets through the proxy
There _may_ be problems with the remote worker also after the last websocket refactor - websocket proxying is _hard_. 
Bit unclear though, the implementation there is significantly different.
> Improve header management on websocket proxying
